### ISSUE TITLE
Choose platform: book down vs hugo

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#1]
We're planning to migrate environmentalcomputing.net to a continuous build system. Either way will be based on Rmd, git, and markdown. The main choice is whether we want it to look like a book -- so use bookdown. Or build using hugo (blogdown). Below are some examples. 

@wcornwell said main challenge from last time, was to find a multilevel dropdown menu structure. 

![image](https://user-images.githubusercontent.com/3589590/109261784-7f1b1780-7854-11eb-99b3-184b1a743007.jpeg)

Hugo & blogdown:

- https://rladiessydney.org/courses/ryouwithme/

Hugo can make multilevel menus, e.g. https://codingnconcepts.com

- https://discourse.gohugo.io/t/how-to-create-multilevel-dropdown-menu-in-hugo/18373
- https://gohugo.io/templates/menu-templates/#menu-entries-from-the-page-s-front-matter

Some bookdown examples:

- https://bookdown.org
- https://geocompr.robinlovelace.net/preface.html#who-this-book-is-for

**Comment by wcornwell** [comment]
not sure we'll need bookdown unless we want more control of the figures: 

```
There are still a few useful features missing in Pandoc’s Markdown at the moment that are necessary to write a relatively complicated document like a book, such as automatic numbering of figures and tables in the HTML output, cross-references of figures and tables, and fine control of the appearance of figures (e.g., currently it is impossible to specify the alignment of images using the Markdown syntax). These are some of the problems that we have addressed in the bookdown package.
```

**Comment by wcornwell** [comment]
i think just hugo for now
