### ISSUE TITLE
Migrate existing content into blogdwon structure

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#10]
Now that we've sorted out the menu structure, and solved the issue with images (#1), we can go ahead and migrate content across. 

It seems there's relatively few issues with existing setup. I'd suggest

- migrate as is, but converting so that each rmd file is a folder with an embedded page "_index.rmd"
- folder names are lower case, no spaces, e.g. `about-this-site`, use hyphens instead of spaces
- put any data/images into the folder for the page. You may need to fix links to images
- check for build errors by running `blogdown::serve_site`, check output. Errors may be caused by
   - out of date code (no longer renders)
   - link to data file is incorrect
 -once building, check images are displaying (easy need to move file into folder and/or change link)

**Comment by fontikar** [comment]
I think we can close this now @dfalster?
