### ISSUE TITLE
Minor markdown formatting issues

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#11]
Looks like blogdown has some more strict definitions compared to knitr for some markdown things.  For example we have to add a space after the ### for headings on some pages

**Comment by fontikar** [comment]
How does one print out code without it rendering in md? e.g in Using R notebooks L104 -106. I'l like to see the code "![](E_C_logo_black_square.png)" printed out next to an the image, rather than it getting rended into an image.
