### ISSUE TITLE
testing deployment

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#12]
this is supposed to be seamless but you never know

**Comment by wcornwell** [comment]
be great to get alistair's feedback on where we're at (esp which pages to revise).  but I think we need to deploy it to a public page first, which *I think* means merging the menu branch back into main?  Or am I wrong about that?  @fontikar @dfalster

**Comment by fontikar** [comment]
Is it too early to deploy? I guess it means troubleshooting the deployment which isn't a bad idea. Perhaps we can merge to master and Alistair download blogdown, install hugo and serve_site()? 

In terms of deployment I assume we want to host via netlify right? if with github pages we have to change the "public/" folder to "docs/". Benefits of Netlify is a custom domain...and other stuff I still don't know yet :D

**Comment by dfalster** [comment]
Ok, we're live!!! 

Netlify integrates with GitHub actions, giving build previews for every push to master and PR request 

Go to https://app.netlify.com/sites/brave-bose-da028a/deploys/ and you'll see all the builds. 

Here's first preview  https://deploy-preview-18--brave-bose-da028a.netlify.app

https://deploy-preview-18--brave-bose-da028a.netlify.app
