### ISSUE TITLE
site domain alias transfer

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#14]

**Comment by wcornwell** [comment]
are we ready to figure this out @dfalster ?

**Comment by dfalster** [comment]
yes! relevant info is here: https://docs.netlify.com/domains-https/custom-domains/

Looks like there's steps on both netlify side and domain side, i.e. whoever you used to register the domain.

**Comment by dfalster** [comment]
We've implemented the redirection. Seems to work!

Only issue is that a warning pops up, suggesting one of the setting isn't quite right


![image](https://user-images.githubusercontent.com/3589590/152405394-898c8409-be59-4e0f-93ff-30fcb9f5c914.jpeg)

When I click on details

![image](https://user-images.githubusercontent.com/3589590/152405657-95653477-b9e4-4f7b-8cc1-c10651124e48.jpeg)

**Comment by dfalster** [comment]
Solved! I needed to renew the SSL/TLS certificate in netlify (under Domain management, HTTPS). 

![image](https://user-images.githubusercontent.com/3589590/152407685-a899f7c6-c81b-4e68-ab35-05c736d914b1.jpeg)
