### ISSUE TITLE
Choose Hugo Theme

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#2]
some options:

- https://themes.gohugo.io/themes/hugo-theme-techdoc/
- https://themes.gohugo.io/themes/hugo-book/

the key issue is to have a collapsible menu like http://environmentalcomputing.net/ so that users can navigate to the right tutorial

see also #1

**Comment by wcornwell** [comment]
https://github.com/alex-shpak/hugo-book seems like the best one i've found

**Comment by wcornwell** [comment]
https://github.com/thingsym/hugo-theme-techdoc could do it too.  not sure how to choose

**Comment by wcornwell** [comment]
any thoughts @fontikar ?

**Comment by wcornwell** [comment]
or @anikobtoth

**Comment by fontikar** [comment]
I am playing around trying to get hugo book

I tried: 
`install_theme(theme = "alex-shpak/hugo-book@master")`
but it looks like its there is no config.toml file to load into R. Probably not written for blogdown interface yet! 

We might just have to do it on the command line? Happy to set a time to do this together. I need to do it for myself too
https://bookdown.org/yihui/blogdown/other-themes.html

**Comment by wcornwell** [comment]
i got a bit further with theme-techdoc but still far from working

**Comment by fontikar** [comment]
We choose hugo-learn! https://github.com/matcornic/hugo-theme-learn!!
