### ISSUE TITLE
Fixing internal links 

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#2]
This involves becoming a shortcode wizard

**Comment by dfalster** [comment]
Just found out that to use shortcodes via Red, need to call via R

```
`r blogdown::shortcode("tweet", "306854385076543488")`
```

See https://rdrr.io/github/rstudio/blogdown/man/shortcode.html

**Comment by wcornwell** [comment]
how do i find the arguments of a shortcode?

**Comment by dfalster** [comment]
Not sure sorry. But I'm also not sure you need short codes for this.

**Comment by wcornwell** [comment]
looks like you don't -- relative paths in classic markdown ```how to organise your data during [data entry](/../getting-started-with-r/data-entry/) ``` seem to work for simple links.  

https://ropensci.org/blog/2019/12/19/urls-tidying/ might be worth trying down the track.
