### ISSUE TITLE
Clean up static folder?

### ISSUE THREAD

**Issue by fontikar** [nicercode/EnvironmentalComputing#22]
There appears to be a lot of duplicated folders in static/ 
I am still learning a bout the function of this folder, is there a way to clean this folder or delete some redundant items? 
I can try delete a folder one by one  and see if the site is affected haha! perhaps @dfalster has some insight?

**Comment by dfalster** [comment]
As far as I know, states is a place to put stuff that may accesses from across the site. But I may be wrong. 

I support cleaning / reducing duplication.
