### ISSUE TITLE
When page name has changed from Wordpress site, add alias 

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#23]
Sometimes the new page may have a slightly different name to the old site. 

By adding an alias, we can redirect the old link to the new link. 

Instructions from https://gohugo.io/content-management/urls/#example-aliases suggest add an alias to the yaml front matter

```
---
aliases:
    - /posts/my-original-url/
    - /2010/01/01/even-earlier-url.html
---
```

So need a list of pages on old and new site for comparisons. 

I'm trying to generate one using `linkchecker` https://linkchecker.github.io/linkchecker/

**Comment by dfalster** [comment]
To run linkchecker, install, then

```
 ~ linkchecker --check-extern  -odot --output="csv" -v http://environmentalcomputing.net > output.csv
 1 thread active,     0 links queued,    0 links in   1 URL checked, runtime 1 seconds
10 threads active,   109 links queued,   20 links in 139 URLs checked, runtime 6 seconds
10 threads active,   100 links queued,   29 links in 139 URLs checked, runtime 11 seconds
10 threads active,   101 links queued,   29 links in 140 URLs checked, runtime 16 seconds
10 threads active,   151 links queued,   63 links in 222 URLs checked, runtime 21 seconds
...
```

Awesome, i now have a list of links form the old site (and found some broken ones)!!!

**Comment by dfalster** [comment]
Here's the list we need to tick off. This is list of pages in the existing wordpress site. We need to find the corresponding page in our current structure, and add the text below in the yaml. As in the example at b517a7205227c38742582ff8ecf7e00f9233776d

- [x] aliases: /analysis-variance-factorial/
- [x] aliases: /analysis-variance-single-factor/
- [x] aliases: /asking-code-questions/
- [x] aliases: /basic-plotting-in-r/
- [x] aliases: /basic-project-management/
- [x] aliases: /categorical-data-analyses/
- [ ] aliases: /cluster-analysis/
- [x] aliases: /coding-skills/
- [x] aliases: /combining-data-sets/
- [ ] aliases: /contingency-tables/
- [x] aliases: /data-entry/
- [x] aliases: /data-manipulation/
- [x] aliases: /data-types-and-structure/
- [x] aliases: /forecasting-time-series/
- [x] aliases: /generalised-linear-models-1/
- [x] aliases: /generalised-linear-models-2/
- [x] aliases: /generalised-linear-models/
- [x] aliases: /getting-started-with-r/
- [x] aliases: /good-practice-for-writing-scripts/
- [x] aliases: /goodness-of-fit-tests/
- [x] aliases: /graphics/
- [x] aliases: /heat-maps/
- [x] aliases: /how-to-interpret-linear-models/
- [x] aliases: /importing-data/
- [x] aliases: /independent-samples-t-test/
- [x] aliases: /installing-r-r-studio/
- [x] aliases: /interpreting-coefficients-in-glms/
- [x] aliases: /intro-to-gams/
- [x] aliases: /introduction-to-mvabund/
- [x] aliases: /linear-models/
- [x] aliases: /linear-regression/
- [ ] aliases: /making-maps-of-your-study-sites/
- [x] aliases: /making-new-variables/
- [ ] aliases: /making-simple-maps/
- [x] aliases: /meta-analysis-1/
- [x] aliases: /meta-analysis-2/
- [x] aliases: /meta-analysis-3/
- [x] aliases: /meta-analysis/
- [x] aliases: /mixed-models-1/
- [x] aliases: /mixed-models-2/
- [x] aliases: /mixed-models-3/
- [x] aliases: /mixed-models/
- [x] aliases: /multidimensional-scaling/
- [x] aliases: /one-continuous-variable/
- [x] aliases: /one-sample-t-test/
- [x] aliases: /paired-t-tests/
- [x] aliases: /plotting-with-ggplot-adding-titles-and-axis-names/
- [x] aliases: /plotting-with-ggplot-altering-the-overall-appearance/
- [x] aliases: /plotting-with-ggplot-bar-plots-with-error-bars/
- [x] aliases: /plotting-with-ggplot-colours-and-symbols/
- [x] aliases: /plotting-with-ggplot-the-basics/
- [x] aliases: /plotting-with-ggplot/
- [x] aliases: /power-analysis/
- [x] aliases: /principal-components-analysis/
- [x] aliases: /reshaping-data/
- [x] aliases: /single-continuous-vs-categorical-variables/
- [x] aliases: /statistics/
- [x] aliases: /subsetting-data/
- [x] aliases: /summarising-data/
- [x] aliases: /t-tests/
- [x] aliases: /two-continuous-variables/
- [x] aliases: /understanding-interactions/
- [x] aliases: /using-loops/
- [x] aliases: /using-rstudio-notebooks/
- [x] aliases: /version-control/
- [x] aliases: /visualising-multivariate-data/
- [x] aliases: /visualising-spatial-data/
- [x] aliases: /visualising-spatial-data/making-interactive-maps-in-r-with-leaflet/
- [x] aliases: /writing-simple-functions/

**Comment by fontikar** [comment]
Thanks @dfalster hope the proccessing didn't take forever! I am on it! Will install linechecker too! how cool!

**Comment by dfalster** [comment]
Hi @fontikar 

I've uploaded a new page with all the aliases we wanted listed (see https://brave-bose-da028a.netlify.app/aliases/). Some don't appear to be working. Running link check, these are the ones that aren't working 

```
linkchecker --output="csv" -v https://brave-bose-da028a.netlify.app/aliases/ > output2.csv
```

```{r}
library(tidyverse)
data <- read_delim("output2.csv", skip = 3, delim = ";")
data %>% filter(result != "200 OK") %>% pull(urlname) %>% writeLines("fails.md")
```

- [x] /asking-code-questions/
- [ ] /cluster-analysis/
- [x] /data-entry/
- [x] /how-to-interpret-linear-models/
- [x] /importing-data/
- [x] /linear-models/
- [x] /linear-regression/
- [ ] /making-maps-of-your-study-sites/
- [x] /making-new-variables/
- [x] /mixed-models/
- [x] /plotting-with-ggplot-bar-plots-with-error-bars/
- [x] /power-analysis/
- [x] /reshaping-data/
- [x] /summarising-data/
- [x] /version-control/

**Comment by fontikar** [comment]
Sorry you had to chase this up and be the middle person! I am on it! I left this thinking they have never changed from the original forgetting they are now under the new nested structure!

**Comment by dfalster** [comment]
Thanks @fontikar

**Comment by dfalster** [comment]
Great work team!
