### ISSUE TITLE
Fix broken links (external)

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#24]
Here is a list of external links that are currently not working

- [x] data-manipulation/subsetting-data/, https://cran.r-project.org/web/packages/dplyr/vignettes/introduction.html
- [x] coding-skills/good-practice/, https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml
- [x] getting-started-with-r/rstudio-notebooks/, https://rviews.rstudio.com/2017/03/15/why-i-love-r-
- [x] getting-started-with-r/rstudio-notebooks/,https://www.rstudio.com/blog/r-
- [x] getting-started-with-r/installing-r-rstudio/, https://www.rstudio.com/training/online-learning/
- [x] graphics/ggplot/, https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf
- [x] about-this-site/, http://data-vocabulary.org/Breadcrumb

**Comment by fontikar** [comment]
Thank you! What a good github actions!!! I didn't check external links! So will check this after fixing internal links in statistics/

**Comment by fontikar** [comment]
All fixed except for last one, can't seem to find that within the directory! 

![Screen Shot 2022-01-31 at 2 12 46 pm](https://user-images.githubusercontent.com/12161802/151734049-83f74749-408a-4d58-b82a-c9818a5f648a.png)

**Comment by dfalster** [comment]
Nice work team, all done!
