### ISSUE TITLE
Add description file

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#27]
Useful for documenting dependencies. 

Use 

```
devtools::install_deps()
```

**Comment by dfalster** [comment]
File has been added. @fontikar Can you add some more details on people, purpose, etc

**Comment by fontikar** [comment]
Need everyone's opinion on what license to use @wcornwell

**Comment by wcornwell** [comment]
good question.  what does ropensci use?

**Comment by wcornwell** [comment]
I guess the question is 

`Allow commercial uses of your work?` or not?

**Comment by wcornwell** [comment]
maybe https://creativecommons.org/licenses/by/4.0/ 

what do you think @dfalster ?

**Comment by dfalster** [comment]
Sounds good (I think)

Do we want anyone in UNSW or any other uni to use it in their courses. That's commercial isn't it?

**Comment by wcornwell** [comment]
> Do we want anyone in UNSW or any other uni to use it in their courses. That's commercial isn't it?

yeah i guess so, so we should allow that

**Comment by dfalster** [comment]
Great work team!
