### ISSUE TITLE
Remove Images/ folder and rewrite history

### ISSUE THREAD

**Issue by fontikar** [nicercode/EnvironmentalComputing#29]

**Comment by dfalster** [comment]
The main motivation here is to cull some very large files, and massively reduce the size of the repository. I've reviewed, and we have some really big files. Here are the largest files in the history

```
➜  EnvironmentalComputing git:(master) ✗ git ls-tree -r -t -l --full-name HEAD | sort -n -k 4 | tail -n 20
➜  EnvironmentalComputing git:(master) ✗ git ls-tree -r -t -l --full-name HEAD | sort -n -k 4 | tail -n 20
1255023	Draft tutorial pages/study-site/_index.html
1641970	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_r.dbf
1801924	Draft tutorial pages/NetCDF/NetCDF.html
1988964	content/Images/Murray-28.jpg
2366625	Draft tutorial pages/Draft_glm/glm.html
2520920	Draft tutorial pages/NetCDF/2015_20151206092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1d_dn-v02.nc
2772927	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_l.dbf
2982785	content/Images/Murray-13.jpg
3140186	content/Images/Murray-26.jpg
5010716	content/Images/site_photo.JPG
5060602	content/Images/group_photo.JPG
5163498	content/Images/DJI_0021.JPG
5529548	content/Images/DJI_0272.JPG
5701888	content/Coding-Skills/asking-code-questions/help-me-help-you.gif
7142632	Ecostats2017/LectureNotes.pdf
7739084	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_l.shp
10187781	Draft tutorial pages/gganimate/MyEBirdData.csv
12487872	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_r.shp
13593905	Draft tutorial pages/Accessing weather data/maxann.asc
13593905	Draft tutorial pages/Accessing weather data/maxann.txt.txt
```

The largest (last 4 ) are more than 10Mb each. This makes the repo really big and cumbersome to work with. Can I filter them out of the history? This would "Rewrite" the history. The implication is that all the hashes would change. Through the commit messages would remain. You'd need to reclone. 

Only makes sense to do this when everyone is kind of finished working on local stuff, as you'll need to reclone the repo. 

Can I go ahead?

- [x] @fontikar 
- [x] @wcornwell

**Comment by dfalster** [comment]
Oh, and hold off making more changes until this is done!

**Comment by dfalster** [comment]
Here's the hit list:

- Images/
- content/Images/
- content/cont
- content/shortcodes
- Ecostats2017
- public/
- Draft\ tutorial\ pages/
- content/Coding-Skills/asking-code-questions/help-me-help-you.gif
- themes/hugo-theme-learn/exampleSite

I was going to remove all Drafts, we can bring them back later if we want to keep

**Comment by dfalster** [comment]
Success! I've reduced the repo size down from 342Mb to 115Mb. This was achieved by removing many large files. 


# Step 1: detect large files

We can find largest files in the current tree using git

```
➜ git ls-tree -r -t -l --full-name HEAD | sort -n -k 4 | tail -n 20

1255023	Draft tutorial pages/study-site/_index.html
1641970	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_r.dbf
1801924	Draft tutorial pages/NetCDF/NetCDF.html
...
2982785	content/Images/Murray-13.jpg
3140186	content/Images/Murray-26.jpg
...
5701888	content/Coding-Skills/asking-code-questions/help-me-help-you.gif
7142632	Ecostats2017/LectureNotes.pdf
7739084	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_l.shp
10187781	Draft tutorial pages/gganimate/MyEBirdData.csv
12487872	Draft tutorial pages/study-site/61395_shp/australia/cstauscd_r.shp
13593905	Draft tutorial pages/Accessing weather data/maxann.asc
13593905	Draft tutorial pages/Accessing weather data/maxann.txt.txt
```

Some files over 13MB! I also checked out some older versions and reran. As files have moved about, this also captures large files in the history.

I also decided to remove the generated html files from the original site, as these were quite large. I found these by checking an old version  and running

```
list.files(".", pattern = ".html", recursive=T, full.names=T)
```

# Step 2 - Remove files

Files are removed using git filter-repo. This program removes specified files from the history. You need to provided the path of the file or folder to remove. Note, this doesn't account for anytimes the file moved. So if that occurred, need to run twice with different paths

To remove a file run this, replacing filename

```
git filter-repo --invert-paths --path filename
```

Beware - when you rewrite history, you change all the commit hashes, so you break collaboration. You'll need to force push and everyone reclone.

# file list

Below is the list of files and folders purgred. Each was prefaced with the command above


- Ecostats2017
- public
- Draft\ tutorial\ pages/
- content/shortcodes
- themes/hugo-theme-learn/exampleSite
- Images
- content/Images/Beaches.png
- content/Images/DJI_0021.JPG
- content/Images/DJI_0272.JPG
- content/Images/drone1.jpg
- content/Images/DSC_2607.jpg
- content/Images/DSC_2842.jpg
- content/Images/DSC_4038.jpg
- content/Images/DSC_7850.jpg
- content/Images/group_photo.JPG
- content/Images/Murray-13.jpg
- content/Images/Murray-26.jpg
- content/Images/Murray-28.jpg
- content/Images/site_photo.JPG
- Coding-Skills/asking-code-questions/help-me-help-you.gif
- 3_Coding\ skills/Asking_code_questions/help-me-help-you.gif
- Statistics/Linear\ models/Linear\ regression/Linear\ regression\ questions/Linear\ regression-questions.docx
- Statistics/Multivariate\ analyses/Multi-choice\ feeding\ assay/Roa\ 1992.pdf
- 5_Statistics/Multivariate analyses/Multi-choice feeding\ assay/Roa\ 1992.pdf
- 5_Statistics/Linear\ models/Linear\ regression/Linear\ regression\ questions/Linear\ regression-questions.docx
- 5_Statistics/Multivariate\ analyses/Multi-choice\ feeding\ assay/Roa\ 1992.pdf
- 5_Statistics/Multivariate\ analyses/Multi-choice\ feeding\ assay/Lockwood\ 1998.pdf
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ maps\ of\ your\ study\ sites/61395\_shp/
- Big\ data 

# generated html from old site

- 0_About this site/About_this_site.html
- 0_About\ this\ site/Site_map.html 
- 1_Getting\ started\ in\ R/0-Getting\ started_introduction/Data_entry_intro.html
- 1_Getting\ started\ in\ R/0-Getting\ started_introduction/Getting_started_intro.html
- 1_Getting\ started\ in\ R/1-Getting\ started\ with\ R\ Studio/Installing_R_and_R_Studio.html
- 1_Getting\ started\ in\ R/2-RStudio_notebooks/R_Studio_notebooks.html
- 1_Getting\ started\ in\ R/2-RStudio_notebooks/R_Studio_notebooks.nb.html
- 1_Getting\ started\ in\ R/3-Basic\ project\ management/Basic_project_managment.html
- 1_Getting\ started\ in\ R/3-Basic\ project\ management/Project_managment.html
- 1_Getting\ started\ in\ R/4-Data\ entry/Data_entry.html
- 1_Getting\ started\ in\ R/5-Data\ structure/Data_types_structure.html
- 1_Getting\ started\ in\ R/6-Importing\ data\ and\ data\ cleaning/Importing_data.html
- 2_Data\ manipulation/Combining\ data/Combining_data.html
- 2_Data\ manipulation/Data\ manipulation_introduction/Data_manipulation_intro.html
- 2_Data\ manipulation/Making\ new\ variables/Making_new_variables.html
- 2_Data\ manipulation/Reshaping\ data/Reshaping_data.html
- 2_Data\ manipulation/Reshaping\ data/Reshaping_data2.html
- 2_Data\ manipulation/Reshaping\ data/Reshaping_method.html
- 2_Data\ manipulation/Subsetting\ data/Subsetting_data.html
- 2_Data\ manipulation/Summarising\ data/Summarising_data.html
- 3_Coding\ skills/Asking_code_questions/Asking_code_questions.html
- 3_Coding\ skills/Coding\ skills_introduction/Coding_skills_intro.html
- 3_Coding\ skills/Functions/Functions.html
- 3_Coding\ skills/Good\ script\ practice/good_script_practice.html
- 3_Coding\ skills/Using\ loops/Loops.html
- 3_Coding\ skills/Version\ control/Version_control.html
- 4_Graphical\ techniques/Base\ R/1-Single,\ continuous\ variable/Single_continuous_variable.html
- 4_Graphical\ techniques/Base\ R/2-Two\ continuous\ variables/Two_continuous_variables.html
- 4_Graphical\ techniques/Base\ R/3-Single\ continuous\ vs\ categorical/Single_continuous_vs_categorical_variables.html
- 4_Graphical\ techniques/Base\ R/Basic\ plotting\ introduction/Basic_plotting_intro.html
- 4_Graphical\ techniques/ggplot/ggplot_basics.html
- 4_Graphical\ techniques/ggplot/ggplot_error_bars.html
- 4_Graphical\ techniques/ggplot/ggplot_formatting_appearance.html
- 4_Graphical\ techniques/ggplot/ggplot_formatting_colour_and_symbols.html
- 4_Graphical\ techniques/ggplot/ggplot_formatting_titles_and_axis.html
- 4_Graphical\ techniques/ggplot/ggplot_intro.html
- 4_Graphical\ techniques/ggplot/ggplot1_basic.html
- 4_Graphical\ techniques/Graphics_intro/Graphics_intro.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Cluster\ analysis/Cluster_analysis.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Cluster\ analysis/Cluster_diagram_method.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Heatmaps/Heatmaps.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/MDS/MDS.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Principal\ components\ analysis/PCA.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Visualising\ multivariate\ data_intro/Visualising_multivariate_data_intro.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Basic\ raster\ data\ manipulation/basic_raster_data_manipulation.html
- 
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ Interactive\ maps/Making_interactive_maps__leaflet_.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ maps\ of\ your\ study\ sites/Making_maps_from_shape_files.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ maps\ of\ your\ study\ sites/Making_maps_of_study_sites.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ simple\ maps\ (ggmap)/Making_simple_maps.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Visualising\ spatial\ data-intro/Visualising_spatial_data_intro.html
- 5_Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency\ tables-questions/Contingency_tables_Q1.html
- 5_Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency\ tables-questions/Contingency_tables_Q2.html
- 5_Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency_tables.html
- 5_Statistics/Categorical\ data\ analyses/Fishers\ exact\ test/Fishers_exact_test_Q1.html
- 5_Statistics/Categorical\ data\ analyses/Fishers\ exact\ test/Fishers_exact_test_Q2.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q1_instructor.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q1.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q2.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q3.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q1.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q2.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q3.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test.html
- 5_Statistics/Forecasting\ with\ time\ series\ data/Forecasting_with_time_series.html
- 5_Statistics/Generalised\ additive\ models/Generalised_additive_models.html
- 5_Statistics/Generalised\ linear\ models/Draft_glm/glm.html
- 5_Statistics/Generalised\ linear\ models/Glm1_binary/Glm1_binary_method.html
- 5_Statistics/Generalised\ linear\ models/Glm1_binary/GLM1_binary.html
- 5_Statistics/Generalised\ linear\ models/Glm2_counts/GLM2_counts.html
- 5_Statistics/Generalised\ linear\ models/Interpreting_glm_coefficients/Interpreting_glm_coefficients.html
- 5_Statistics/Linear\ models/ANOVA-factorial/ANOVA_factorial.html
- 5_Statistics/Linear\ models/ANOVA-nested/ANOVA_nested_method.html
- 5_Statistics/Linear\ models/ANOVA-single\ factor/ANOVA_single_factor.html
- 5_Statistics/Linear\ models/Interpreting\ coefficients/Interpret_linear_models.html
- 5_Statistics/Linear\ models/Linear\ models_introduction/Linear_models_introduction.html
- 5_Statistics/Linear\ models/Linear\ regression/Linear\ regression\ questions/Linear_regression_Q1.html
- 5_Statistics/Linear\ models/Linear\ regression/Linear_regression.html
- 5_Statistics/Linear\ models/Linear\ regression/Linear_regression.nb.html
- 5_Statistics/Linear\ models/Understanding\ interactions/Understanding_interactions.html
- 5_Statistics/Meta\ analysis/Meta_analysis_1.html
- 5_Statistics/Meta\ analysis/Meta_analysis_2.html
- 5_Statistics/Meta\ analysis/Meta_analysis_3.html
- 5_Statistics/Meta\ analysis/Meta-analysis_intro.html
- 5_Statistics/Mixed\ models/Mixed_models_1.html
- 5_Statistics/Mixed\ models/Mixed_models_introduction.html
- 5_Statistics/Multivariate\ analyses/Intro\ to\ mvabund/Intro_to_mvabund.html
- 5_Statistics/Sampling\ and\ experimental\ design/Power\ analysis/Power_analysis.html
- 5_Statistics/Sampling\ and\ experimental\ design/Power\ analysis/RPower.html
- 5_Statistics/Statistics_intro/Statistics_introduction.html
- 5_Statistics/t\ tests/One\ sample\ t-test/One_sample_t_test_method.html
- 5_Statistics/t\ tests/One\ sample\ t-test/One_sample_t_test.html
- 5_Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q1.html
- 5_Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q2.html
- 5_Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q3.html
- 5_Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q4.html
- 5_Statistics/t\ tests/Paired\ t-test/Paired_t_test.html
- 5_Statistics/t\ tests/Two\ sample\ t-test/Independent_samples_t_test.html
- 5_Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q1.html
- 5_Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q2.html
- 5_Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q3.html
- 5_Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q4.html
- Draft\ tutorial\ pages/Accessing\ weather\ data/Working_with_weather_variables.html
- Draft\ tutorial\ pages/gganimate/gganimate2.nb.html
- Draft\ tutorial\ pages/NetCDF/NetCDF.html
- Draft\ tutorial\ pages/Survival\ analyses/Survival_analysis.html
-  
- About this site/About_this_site.html
- About this site/Site_map.html
- Big data/Accessing weather data/Working_with_weather_variables.html
- Big data/NetCDF/NetCDF.html
- Data entry and manipulation/0-Data manipulation_introduction/Data_manipulation_intro.html
- Data entry and manipulation/1-Data entry/Data_entry.html
- Data entry and manipulation/2-Importing data and data cleaning/Importing_data.html
- Data entry and manipulation/3-Data structure/Data_types_structure.html
- Data entry and manipulation/5-Reshaping data/Reshaping_data.html
- Data entry and manipulation/5-Reshaping data/Reshaping_data2.html
- Data entry and manipulation/5-Reshaping data/Reshaping_method.html
- Data entry and manipulation/6-Data wrangling with dplyr/Combining_data.html
- Data entry and manipulation/6-Data wrangling with dplyr/Subsetting_data.html
- Data entry and manipulation/6-Data wrangling with dplyr/Summarising_data.html
- Data entry and manipulation/Making new variables/Making_new_variables.html
- Getting started in R/Basic project management/Basic_project_managment.html
- Getting started in R/Basic project management/Project_managment.html
- Getting started in R/Functions/Functions.html
- Getting started in R/Getting started with R Studio/Getting_started_R_Studio.html
- Getting started in R/Good script practice/good_script_practice.html
- Graphical techniques/Base R/1-Single, continuous variable/Single_continuous_variable.html
- Graphical techniques/Base R/2-Two continuous variables/Two_continuous_variables.html
- Graphical techniques/Base R/3-Single continuous vs categorical/Single_continuous_vs_categorical_variables.html
- Graphical techniques/Base R/Basic plotting introduction/Basic_plotting_intro.html
- Graphical techniques/ggplot/ggplot_basics.html
- Graphical techniques/ggplot/ggplot_error_bars.html
- Graphical techniques/ggplot/ggplot_formatting_appearance.html
- Graphical techniques/ggplot/ggplot_formatting_colour_and_symbols.html
- Graphical techniques/ggplot/ggplot_formatting_titles_and_axis.html
- Graphical techniques/ggplot/ggplot_intro.html
- Graphical techniques/ggplot/ggplot1_basic.html
- Graphical techniques/Graphics_intro/Graphics_intro.html
- Graphical techniques/Visualising multivariate data sets/Cluster analysis/Cluster_analysis.html
- Graphical techniques/Visualising multivariate data sets/Cluster analysis/Cluster_diagram_method.html
- Graphical techniques/Visualising multivariate data sets/Heatmaps/Heatmaps.html
- Graphical techniques/Visualising multivariate data sets/MDS/MDS.html
- Graphical techniques/Visualising multivariate data sets/Principal components analysis/PCA.html
- Graphical techniques/Visualising multivariate data sets/Visualising multivariate data_intro/Visualising_multivariate_data_intro.html
- Graphical techniques/Visualising spatial data/Making simple maps/Making_simple_maps.html
- Graphical techniques/Visualising spatial data/Visualising spatial data-intro/Visualising_spatial_data_intro.html
- Statistics/Categorical data analyses/Contingency tables/Contingency tables-questions/Contingency_tables_Q1.html
- Statistics/Categorical data analyses/Contingency tables/Contingency tables-questions/Contingency_tables_Q2.html
- Statistics/Categorical data analyses/Contingency tables/Contingency_tables.html
- Statistics/Categorical data analyses/Fishers exact test/Fishers_exact_test_Q1.html
- Statistics/Categorical data analyses/Fishers exact test/Fishers_exact_test_Q2.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness of fit test_Q1_instructor.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness of fit test_Q1.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness of fit test_Q2.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness of fit test_Q3.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q1.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q2.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q3.html
- Statistics/Categorical data analyses/Goodness of fit test/Goodness_of_fit_test.html
- Statistics/Forecasting with time series data/Forecasting_with_time_series.html
- Statistics/Generalised linear models/Draft_glm/glm.html
- Statistics/Generalised linear models/Glm1_binary/Glm1_binary_method.html
- Statistics/Generalised linear models/Glm1_binary/GLM1_binary.html
- Statistics/Generalised linear models/Glm2_counts/GLM2_counts.html
- Statistics/Linear models/ANOVA-factorial/ANOVA_factorial.html
- Statistics/Linear models/ANOVA-nested/ANOVA_nested_method.html
- Statistics/Linear models/ANOVA-single factor/ANOVA_single_factor.html
- Statistics/Linear models/Linear models_introduction/Linear_models_introduction.html
- Statistics/Linear models/Linear regression/Linear regression questions/Linear_regression_Q1.html
- Statistics/Linear models/Linear regression/Linear_regression.html
- Statistics/Linear models/Understanding interactions/Understanding_interactions.html
- Statistics/Mixed models/Mixed_models_1.html
- Statistics/Mixed models/Mixed_models_introduction.html
- Statistics/Multivariate analyses/Intro to mvabund/Intro_to_mvabund.html
- Statistics/Statistics_intro/Statistics_introduction.html
- Statistics/Survival analyses/Survival_analysis.html
- Statistics/t tests/One sample t-test/One_sample_t_test_method.html
- Statistics/t tests/One sample t-test/One_sample_t_test.html
- Statistics/t tests/Paired t-test/Paired t test questions/Paired_t_test_Q1.html
- Statistics/t tests/Paired t-test/Paired t test questions/Paired_t_test_Q2.html
- Statistics/t tests/Paired t-test/Paired t test questions/Paired_t_test_Q3.html
- Statistics/t tests/Paired t-test/Paired t test questions/Paired_t_test_Q4.html
- Statistics/t tests/Paired t-test/Paired_t_test.html
- Statistics/t tests/Two sample t-test/Independent_samples_t_test.html
- Statistics/t tests/Two sample t-test/Two sample t-test questions/Two_sample_t_test_Q1.html
- Statistics/t tests/Two sample t-test/Two sample t-test questions/Two_sample_t_test_Q2.html
- Statistics/t tests/Two sample t-test/Two sample t-test questions/Two_sample_t_test_Q3.html
- Statistics/t tests/Two sample t-test/Two sample t-test questions/Two_sample_t_test_Q4.html
- 
- About\ this\ site/About_this_site.html
- About\ this\ site/Site_map.html
- Big\ data/Accessing\ weather\ data/Working_with_weather_variables.html
- Big\ data/NetCDF/NetCDF.html
- Data\ entry\ and\ manipulation/0-Data\ manipulation_introduction/Data_manipulation_intro.html
- Data\ entry\ and\ manipulation/1-Data\ entry/Data_entry.html
- Data\ entry\ and\ manipulation/2-Importing\ data\ and\ data\ cleaning/Importing_data.html
- Data\ entry\ and\ manipulation/3-Data\ structure/Data_types_structure.html
- Data\ entry\ and\ manipulation/5-Reshaping\ data/Reshaping_data.html
- Data\ entry\ and\ manipulation/5-Reshaping\ data/Reshaping_data2.html
- Data\ entry\ and\ manipulation/5-Reshaping\ data/Reshaping_method.html
- Data\ entry\ and\ manipulation/6-Data\ wrangling\ with\ dplyr/Combining_data.html
- Data\ entry\ and\ manipulation/6-Data\ wrangling\ with\ dplyr/Subsetting_data.html
- Data\ entry\ and\ manipulation/6-Data\ wrangling\ with\ dplyr/Summarising_data.html
- Data\ entry\ and\ manipulation/Making\ new\ variables/Making_new_variables.html
- Getting\ started\ in\ R/Basic\ project\ management/Basic_project_managment.html
- Getting\ started\ in\ R/Basic\ project\ management/Project_managment.html
- Getting\ started\ in\ R/Functions/Functions.html
- Getting\ started\ in\ R/Getting\ started\ with\ R\ Studio/Getting_started_R_Studio.html
- Getting\ started\ in\ R/Good\ script\ practice/good_script_practice.html
- Graphical\ techniques/Base\ R/1-Single,\ continuous\ variable/Single_continuous_variable.html
- Graphical\ techniques/Base\ R/2-Two\ continuous\ variables/Two_continuous_variables.html
- Graphical\ techniques/Base\ R/3-Single\ continuous\ vs\ categorical/Single_continuous_vs_categorical_variables.html
- Graphical\ techniques/Base\ R/Basic\ plotting\ introduction/Basic_plotting_intro.html
- Graphical\ techniques/ggplot/ggplot_basics.html
- Graphical\ techniques/ggplot/ggplot_error_bars.html
- Graphical\ techniques/ggplot/ggplot_formatting_appearance.html
- Graphical\ techniques/ggplot/ggplot_formatting_colour_and_symbols.html
- Graphical\ techniques/ggplot/ggplot_formatting_titles_and_axis.html
- Graphical\ techniques/ggplot/ggplot_intro.html
- Graphical\ techniques/ggplot/ggplot1_basic.html
- Graphical\ techniques/Graphics_intro/Graphics_intro.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/Cluster\ analysis/Cluster_analysis.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/Cluster\ analysis/Cluster_diagram_method.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/Heatmaps/Heatmaps.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/MDS/MDS.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/Principal\ components\ analysis/PCA.html
- Graphical\ techniques/Visualising\ multivariate\ data\ sets/Visualising\ multivariate\ data_intro/Visualising_multivariate_data_intro.html
- Graphical\ techniques/Visualising\ spatial\ data/Making\ simple\ maps/Making_simple_maps.html
- Graphical\ techniques/Visualising\ spatial\ data/Visualising\ spatial\ data-intro/Visualising_spatial_data_intro.html
- Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency\ tables-questions/Contingency_tables_Q1.html
- Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency\ tables-questions/Contingency_tables_Q2.html
- Statistics/Categorical\ data\ analyses/Contingency\ tables/Contingency_tables.html
- Statistics/Categorical\ data\ analyses/Fishers\ exact\ test/Fishers_exact_test_Q1.html
- Statistics/Categorical\ data\ analyses/Fishers\ exact\ test/Fishers_exact_test_Q2.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q1_instructor.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q1.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q2.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q3.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q1.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q2.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q3.html
- Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test.html
- Statistics/Forecasting\ with\ time\ series\ data/Forecasting_with_time_series.html
- Statistics/Generalised\ linear\ models/Draft_glm/glm.html
- Statistics/Generalised\ linear\ models/Glm1_binary/Glm1_binary_method.html
- Statistics/Generalised\ linear\ models/Glm1_binary/GLM1_binary.html
- Statistics/Generalised\ linear\ models/Glm2_counts/GLM2_counts.html
- Statistics/Linear\ models/ANOVA-factorial/ANOVA_factorial.html
- Statistics/Linear\ models/ANOVA-nested/ANOVA_nested_method.html
- Statistics/Linear\ models/ANOVA-single\ factor/ANOVA_single_factor.html
- Statistics/Linear\ models/Linear\ models_introduction/Linear_models_introduction.html
- Statistics/Linear\ models/Linear\ regression/Linear\ regression\ questions/Linear_regression_Q1.html
- Statistics/Linear\ models/Linear\ regression/Linear_regression.html
- Statistics/Linear\ models/Understanding\ interactions/Understanding_interactions.html
- Statistics/Mixed\ models/Mixed_models_1.html
- Statistics/Mixed\ models/Mixed_models_introduction.html
- Statistics/Multivariate\ analyses/Intro\ to\ mvabund/Intro_to_mvabund.html
- Statistics/Statistics_intro/Statistics_introduction.html
- Statistics/Survival\ analyses/Survival_analysis.html
- Statistics/t\ tests/One\ sample\ t-test/One_sample_t_test_method.html
- Statistics/t\ tests/One\ sample\ t-test/One_sample_t_test.html
- Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q1.html
- Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q2.html
- Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q3.html
- Statistics/t\ tests/Paired\ t-test/Paired\ t\ test\ questions/Paired_t_test_Q4.html
- Statistics/t\ tests/Paired\ t-test/Paired_t_test.html
- Statistics/t\ tests/Two\ sample\ t-test/Independent_samples_t_test.html
- Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q1.html
- Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q2.html
- Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q3.html
- Statistics/t\ tests/Two\ sample\ t-test/Two\ sample\ t-test\ questions/Two_sample_t_test_Q4.html
- 
- 0_About\ this\ site/About_this_site.html
- 4_Graphical\ techniques/Visualising\ multivariate\ data\ sets/Visualising\ multivariate\ data_intro/Visualising_multivariate_data_intro.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ Interactive\ maps\ (leaflet)/Making_interactive_maps__leaflet_.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ maps\ of\ your\ study\ sites/Making_maps_of_study_sites.html
- 4_Graphical\ techniques/Visualising\ spatial\ data/Making\ simple\ maps\ (ggmap)/Making_simple_maps.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness\ of\ fit\ test_Q1_instructor.html
- 5_Statistics/Categorical\ data\ analyses/Goodness\ of\ fit\ test/Goodness_of_fit_test_questions/Goodness_of_fit_test_Q2.html
