### ISSUE TITLE
Refining look of the site including logo etc

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#3]

**Comment by wcornwell** [comment]
<img width="837" alt="Screen Shot 2022-01-25 at 9 21 52 am" src="https://user-images.githubusercontent.com/5534161/150874928-1d91363c-b046-4c91-b25f-3652f53e23e6.png">
hmmmm

**Comment by dfalster** [comment]
I've removed the learn bit, but we still want a name in there somewhere 

![image](https://user-images.githubusercontent.com/3589590/150898961-585082d0-6fe9-4ba8-b106-a2e3e19d2805.jpeg)

**Comment by wcornwell** [comment]
Hmmmm....To do this properly, it should be a svg: https://designbundles.net/design-school/how-to-create-svgs-in-adobe-illustrator

**Comment by dfalster** [comment]
Here's where t is

![image](https://user-images.githubusercontent.com/3589590/151905266-56b51030-79ea-4c7b-b919-83b57140e37b.jpeg)
