### ISSUE TITLE
rendered outputs are too large on big screen

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#30]
Looking at the page with a larger monitor, the rendered images rescale to be quite big and take up the page. They should probably be smaller. WDYT @wcornwell @fontikar 

![image](https://user-images.githubusercontent.com/3589590/152059480-7374e109-f4d7-406f-9c03-a421410e398e.jpeg)

**Comment by wcornwell** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/figure-size.html

**Comment by wcornwell** [comment]
seems like bookdown controls dynamic figure size based on % of the width of the html element, so we might be stuck with this problem unless a small tweak of the out.width thing `{r, out.width="50%", fig.cap="A nice image."}` helps.

**Comment by fontikar** [comment]
![Screen Shot 2022-02-02 at 12 06 33 pm](https://user-images.githubusercontent.com/12161802/152077234-5c03308c-5b8f-48bc-b844-a1e52a2b264f.png)


Hmmm strange, its not rendering me for me after fetching the latest rebuild! I always wondered what was going on with the nice squares. Should I try rebuilding?? @dfalster

**Comment by dfalster** [comment]
Strange. 

Works on my machine and on https://deploy-preview-18--brave-bose-da028a.netlify.app/statistics/gams/

You shouldn't need to rebuild (i.e. reknit). 

Try deleting "public" then `blogdown::build_site()`

**Comment by dfalster** [comment]
We'll leave this as is.
