### ISSUE TITLE
Requests for new content

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#33]
Maybe we could have a link for users who find mistakes or want to request new topics?  This could go to (this?) github issue page?

**Comment by dfalster** [comment]
Yes, but let's separate new content and mistakes


For new content, we can step a template for an issue on GitHub . The link then starts a new issue with correct labels and following a template.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

For mistakes, we could do something similar, with a template. But we could also use the feature in the hugo site. Each page has an "Edit this page" link. This takes you to a link to edit the html page under content. We probably want to change it to edit the Rmd. Then need a trigger to rebuild the html. 

Either way - everything should be encouraged to come via a PR

**Comment by fontikar** [comment]
Was going to tackle this but I don't think I had admin rights! Happy to draft one regardless :D

**Comment by wcornwell** [comment]
this is done?
