### ISSUE TITLE
Pathway way for reporting mistakes

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#34]
From #33, want a good workflow for reporting mistakes and updating content. 

A [template for new issue](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) on GitHub would be a good start. 

Also, current site has an "Edit this page" link in each page. This takes you to a link to edit the html page under content. We probably want to change it to edit the Rmd. Then need a trigger to rebuild the html. Also change to "Report issue?"

![image](https://user-images.githubusercontent.com/3589590/152459484-646d29e1-d070-4004-9e2a-9e597e9b92ef.jpeg)

**Comment by wcornwell** [comment]
Maybe just need a small modification here: https://github.com/nicercode/EnvironmentalComputing/blob/ca84bf596b59376d4c23a94926f773e1c5541785/themes/hugo-theme-learn/layouts/partials/header.html#L56 ?

**Comment by wcornwell** [comment]
done?
