### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#35]
should migrate this over somehow

**Comment by dfalster** [comment]
favicon - is this the icon in the browser bar?

**Comment by wcornwell** [comment]
yup

**Comment by dfalster** [comment]
Looks straight forward, just put in static folder.

https://stackoverflow.com/questions/42043648/where-do-i-put-my-favicon-with-hugo

Is it this file? https://github.com/cornwell-lab-unsw/EnvironmentalComputing/blob/master/E_C_Logo_black_square-300x265.png

**Comment by fontikar** [comment]
Is there a way to access the old website? I am trying to see what favicons we had there? I think we can delete  https://github.com/cornwell-lab-unsw/EnvironmentalComputing/blob/master/E_C_Logo_black_square-300x265.png, it used to be in the README but we have a new and improve logo now!

**Comment by fontikar** [comment]
![Screen Shot 2022-02-08 at 11 48 24 am](https://user-images.githubusercontent.com/12161802/152896836-ca443ccd-10c1-4ee7-9163-9cf6b9aba967.png)
I managed to do it!! Had to add back in header.html and favicon.html!

**Comment by dfalster** [comment]
Awesome! Alas not showing here yet. Is it showing in your browser?

**Comment by wcornwell** [comment]
Latest commit didn't deploy successfully?

**Comment by fontikar** [comment]
<img width="1209" alt="Screen Shot 2022-02-09 at 9 17 30 am" src="https://user-images.githubusercontent.com/12161802/153084996-dc6b1a3b-4baa-44d4-bd2b-1701a1795080.png">
It is deployed on me end!? But as I said in slack, for some reason layouts/partials didn't push to the repo! I will add this manually via Github itself.

**Comment by fontikar** [comment]
<img width="823" alt="Screen Shot 2022-02-09 at 9 35 01 am" src="https://user-images.githubusercontent.com/12161802/153087105-d52787a8-1912-4c4f-a261-1b37ee56a877.png">

This appears to be the issue, the favicon.html file is greyed out!

**Comment by fontikar** [comment]
No idea why the favicon is not showing up now that everything needed is in the repo (favicon.html, header.html, favicon.png)!

**Comment by fontikar** [comment]
The mystery continues and sounds like it may have to do with netilify: https://answers.netlify.com/t/favicon-not-showing-on-netlify/16349/6  

@dfalster do you mind trying to downloading the deploy to check if it contains the favicon files?: https://docs.netlify.com/site-deploys/manage-deploys/#download-a-deploy

Otherwise we can try this:
![Screen Shot 2022-02-09 at 12 11 48 pm](https://user-images.githubusercontent.com/12161802/153102803-068751dc-6515-403b-9699-1a00f51ad16f.png)

**Comment by dfalster** [comment]
Working locally on my machine

![image](https://user-images.githubusercontent.com/3589590/153105097-e4592ca7-9b78-4de5-8f8d-faaec82b6163.jpeg)

But not on any of the netlify sites 

@fontikar I've booked over the code and can't fault it.

Also, the favicon image is on the server. You can access directly via https://environmentalcomputing.net/images/favicon.png

**Comment by dfalster** [comment]
And just to check, i downloaded the deploy to check what was in there (good tip BTW)

The file is in there
![image](https://user-images.githubusercontent.com/3589590/153109517-43efee5b-b427-4e63-b0e4-7d927de4746c.jpeg)

As is the links

![image](https://user-images.githubusercontent.com/3589590/153109575-979f52b0-55e8-49bf-960a-88654647720b.jpeg)

**Comment by fontikar** [comment]
Bummer, I'm stumped! I will post to that thread and see how where it lands! Thanks for all the checks @dfalster :)

**Comment by fontikar** [comment]
> And just to check, i downloaded the deploy to check what was in there (good tip BTW)
> 
> The file is in there ![image](https://user-images.githubusercontent.com/3589590/153109517-43efee5b-b427-4e63-b0e4-7d927de4746c.jpeg)
> 
> As is the links
> 
> ![image](https://user-images.githubusercontent.com/3589590/153109575-979f52b0-55e8-49bf-960a-88654647720b.jpeg)

Actually @dfalster how about partials files? Do you mind having a look in layouts/partials/ and see if header.html and favicon.html is there? Those are the partials that call on images/favicon! From which file is the second screenshot taken?

**Comment by dfalster** [comment]
Hi @fontikar - at the end of the deploy stage, each page has by now been rendered into  a standalone page. So all the partials and theme stuff is gone.  

So you shouldn't have partials there. 

My point about is that if you look in the html files, you see the partial has done its work. The appropriate (I think) code has been inserted into each page for the page icon, exactly where the favicon partial would place it.

**Comment by fontikar** [comment]
Can you both confirm you can see the favicon? It appears to be working now?! 

https://answers.netlify.com/t/favicon-not-showing-on-netlify/16349/18

**Comment by dfalster** [comment]
Yes, it's there, nice one!!! Did you change anything?

**Comment by fontikar** [comment]
No no I suppose there maybe a lag to get things on a server?!

**Comment by wcornwell** [comment]
done
