### ISSUE TITLE
adding lots of yamls to the top of rmd files to finish the hierarchy

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#5]

**Comment by wcornwell** [comment]
this is migration of existing content

**Comment by fontikar** [comment]
All content *except* ~~Spatial::simple-maps~~ and Spatial::study-site has been migrated!  .yml added and structure is there!

**Comment by fontikar** [comment]
I think we can also close this! We can revisit draft pages and the study-site page now that we know what the drill is! @wcornwell @dfalster thoughts?
