### ISSUE TITLE
special section for datasets

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#6]

**Comment by fontikar** [comment]
Trying this solution! https://stackoverflow.com/questions/62372091/add-download-button-to-r-blogdown-website

**Comment by fontikar** [comment]
Wahoo it works!

**Comment by fontikar** [comment]
I always forget to refer to the issue number but cbf84a6 has created a dedicated section for datasets. 
But @dfalster has proposed a nice solution too:

> If the datasets are small, people could read.csv straight from the web page, or we could provide a function to download it

```
read.csv("https://deploy-preview-18--brave-bose-da028a.netlify.app/data-manipulation/subsetting-data/Bats_data.csv")

download.file("https://deploy-preview-18--brave-bose-da028a.netlify.app/data-manipulation/subsetting-data/Bats_data.csv", "Bats_data.csv")

read.csv("Bats_data.csv")```
