### ISSUE TITLE
Remove <br>

### ISSUE THREAD

**Issue by dfalster** [nicercode/EnvironmentalComputing#7]
Many pages have <br> inserted to create extra whitespace,. These aren't need and should be removed

**Comment by NaincyKumariKnoldus** [comment]
Hey @dfalster Can I please do this?

**Comment by dfalster** [comment]
hi @NaincyKumariKnoldus , Thanks for the offer. Can you expand on your interests n the project and why you'd want to help?

In any case, this job is on hold, until all content has been migrated.

**Comment by NaincyKumariKnoldus** [comment]
Hey @dfalster I like to do open source contribution. This is the reason why I also want to contribute to your project.

**Comment by fontikar** [comment]
Hi @NaincyKumariKnoldus! 👋  Thanks for showing interest in this project and offering a helping hand! Apologises I didn't see your offer before but I have just resolved this issue! At this stage, the project is still very much in early development so we have not written community contributing guidelines! We will work on those once the project takes a bit more shape, we would be more than happy to consider any help! Again, thank you!
